# Generated by Django 4.0 on 2021-12-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_testmodel_y'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='testmodel',
            constraint=models.UniqueConstraint(fields=('x', 'y'), name='test_constraint'),
        ),
    ]
